config/routes.rb
Rails.application.routes.draw do
  root 'incidentes#index'
  get 'incidentes/sobre'
  get 'incidentes/grafica'

  resources :incidentes

end

app/models/incidente.rb
class Incidente < ActiveRecord::Base

	# Presencia de atributos
	
	validates_presence_of :asunto, message: "no puede estar vacío."
	validates_presence_of :descripcion, message: "no puede estar vacío."
	validates_presence_of :responsable, message: "no puede estar vacío."
    validates_presence_of :tipo, message: "no puede estar vacío."
	validates_presence_of :prioridad, message: "no puede estar vacío."

	# Largo de los atributos

	validates :asunto, length: { maximum: 60, message: "solo permite hasta 60 caracteres." }
	validates :descripcion, length: { maximum: 500, message: "permite un máximo de 500 caracteres." }
	validates :responsable, length: { maximum: 40, message: "solo permite hasta 40 caracteres." }
	validates :prioridad, length: { is: 1, message: "debe ser 1, 2 o 3." }

	# Otros

	# validates :responsable, format: { with: /\A[a-zA-Z]+\z/,
 	# message: "solo se permite el ingreso de letras." }
	
	validates :tipo, inclusion: { in: %w(Problema Soporte Bug Error problema soporte bug error),
    message: "%{value} no es un tipo de incidente válido" }


	# Valido que Prioridad sea un número
		
	validates :prioridad, numericality: true


    # Valido que Prioridad sea un número del 1 al 3

    validates :prioridad, inclusion: { in: 1..3 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
      @titulo = "Home - Dashboard de Incidentes"
      @incidentes = Incidente.all
  end
  def edit
      @titulo = "Editar Incidente - Dashboard de Incidentes"
      @incidente = Incidente.find(params[:id])
  end
  def update
      @titulo = "Editar Incidente - Dashboard de Incidentes"
      @incidente = Incidente.find(params[:id])
      @incidente = Incidente.update_attributes(params[:incidente])
      redirect_to incidentes_path
  end
  def about
    @titulo = "About - Dashboard de Incidentes"
  end
end

app/controllers/incidentes_controller.rb
class IncidentesController < ApplicationController
  before_action :set_incidente, only: [:show, :edit, :update, :destroy]


  # GET /incidentes
  # GET /incidentes.json
  def index

    # Título de la página
    @titulo = "Inicio" 
    
    # Lógica de busqueda  
    @q = Incidente.ransack(params[:q])

    @incidentes = @q.result(distinct: true).page params[:page]   
    @q.build_condition 

    # Paginación  

  end

  def grafica

    # Título de la página
    @titulo = "Gráfica de incidentes"   
    
    # Recursos de busqueda para cargar datos en gráfica
    @q = Incidente.ransack(params[:q])
    @incidentes = @q.result(distinct: true)  
    @q.build_condition 
  end

  # GET /incidentes/1
  # GET /incidentes/1.json
  def show

    # Título de la página
    @titulo = "Contenido del incidente"   

    @incidentes = Incidente.all

  end

  # GET /incidentes/new
  def new

    # Título de la página
    @titulo = "Nuevo incidente"   

    @incidente = Incidente.new
  end

  # GET /incidentes/1/edit
  def edit

    # Título de la página
    @titulo = "Actualizar incidente"   
  end

  def sobre

    # Título de la página
    @titulo = "Sobre esta aplicación"   

  end

  # POST /incidentes
  # POST /incidentes.json
  def create
    @incidente = Incidente.new(incidente_params)

    respond_to do |format|
      if @incidente.save
        format.html { redirect_to @incidente, notice: 'Incidente ha sido creado correctamente.' }
        format.json { render :show, status: :created, location: @incidente }
      else
        format.html { render :new }
        format.json { render json: @incidente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidentes/1
  # PATCH/PUT /incidentes/1.json
  def update
    respond_to do |format|
      if @incidente.update(incidente_params)
        format.html { redirect_to @incidente, notice: 'Incidente actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @incidente }
      else
        format.html { render :edit }
        format.json { render json: @incidente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidentes/1
  # DELETE /incidentes/1.json
  def destroy
    @incidente = Incidente.find(params[:id])
    @incidente.destroy
    respond_to do |format|
      format.html { redirect_to incidentes_url, notice: 'Incidente eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incidente
      @incidente = Incidente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incidente_params
      params.require(:incidente).permit(:asunto, :descripcion, :responsable, :tipo, :prioridad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
# Defino la función "sortable" para ordenar una tabla clickeando en el título de su columna

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incidentes_helper.rb
module IncidentesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/incidentes/_condition_fields.html.erb
<!-- Construcción de condiciones de filtro para la busqueda de incidentes -->
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select %>
  <% end %>
  <%= f.predicate_select only: [:cont, :eq, :gteq, :lteq] %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value, placeholder: "Buscar..."  %>
  <% end %>
</div>

app/views/incidentes/_form.html.erb
<!-- Formulario que se invoca cuando se gestiona un incidente -->

<%= form_for(@incidente) do |f| %>
  <% if @incidente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incidente.errors.count, "error") %> prohibited this incidente from being saved:</h2>

      <ul>
      <% @incidente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asunto %><br>
    <%= f.text_field :asunto %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :responsable %><br>
    <%= f.text_field :responsable %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.select :tipo, options_for_select([["Problema", "Problema"], ["Soporte", "Soporte"],["Bug", "Bug"],["Error", "Error"]]) %>
  </div>
  <div class="field">
    <%= f.label :prioridad %><br>
    <%= f.select :prioridad, options_for_select([["1", "1"], ["2", "2"],["3", "3"]]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incidentes/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <ul class="nav navbar-nav navbar-right">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Inicio', root_path %></li>
          <li><%= link_to 'Gráfica', incidentes_grafica_path %></li>
          <li><%= link_to 'Sobre esta aplicación', incidentes_sobre_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/incidentes/about.html.erb
<h1>Sobre este proyecto</h1>
<p>Holaaa :D</p>

app/views/incidentes/edit.html.erb
<div class="jumbotron center">
	<h1>Actualizar Incidente</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @incidente %> |
<%= link_to 'Atrás', incidentes_path %>

</div>

app/views/incidentes/grafica.html.erb
<div class="row">
  <div class="col-xs-6">
    <h3>Gráfica de Incidentes</h3>
    <%= pie_chart @incidentes.group(:tipo).count %>
  </div>
</div>

app/views/incidentes/index.html.erb
<p id="notice"><%= notice %></p>
    <h2>Lista de incidentes</h2>

   <div class="jumbotron center">

  <div>
    <h3><span class="glyphicon glyphicon-filter" aria-hidden="true"></span> Filtrar incidentes</h3>

<!-- Filtro de busqueda -->
  <%= search_form_for @q do |f| %>
    <%= f.condition_fields do |c| %>
      <%= render "condition_fields", f: c %>
    <% end %>
    <%= f.submit "Filtrar"%>
  <% end %>
  
  <!-- Generación de tabla de incidentes -->
  </div>
   <div class="panel-heading">
      <table class="table">
        <thead>
          <tr>
            <th><%= sort_link @q, :id, "ID" %></th>
            <th><%= sort_link @q, :asunto, "Asunto" %></th>
            <th><%= sort_link @q, :descripcion, "Descripcion" %></th>
            <th><%= sort_link @q, :responsable, "Responsable" %></th>
            <th><%= sort_link @q, :tipo, "Tipo" %></th>
            <th><%= sort_link @q, :prioridad, "Prioridad" %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @incidentes.each do |incidente| %>
            <tr>
              <td><%= incidente.id %></td>
              <td><%= incidente.asunto %></td>
              <td><%= incidente.descripcion %></td>
              <td><%= incidente.responsable %></td>
              <td><%= incidente.tipo %></td>
              <td><%= incidente.prioridad %></td>
              <td><%= link_to 'Mostrar', incidente %></td>
              <td><%= link_to 'Editar', edit_incidente_path(incidente) %></td>
              <td><%= link_to "Borrar", incidente_path(incidente), method: :delete, form_class: 'destroy_button', data: { confirm: "Se eliminara el incidente de forma permanente ¿Desea continuar?" } %>  
              </td>      
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @incidentes %>
      <br>
      </div>
          <button type="button" class="btn btn-default btn-lg" onclick="location.href='<%= new_incidente_path %>'">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Nuevo incidente
          </button>
    </div>

app/views/incidentes/new.html.erb
<div class="jumbotron center">
  
<h1>Crear Incidente</h1>

<%= render 'form' %>

<%= link_to 'Atrás', incidentes_path %>
<div>

app/views/incidentes/show.html.erb
<div class="jumbotron center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Asunto:</strong>
  <%= @incidente.asunto %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @incidente.descripcion %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @incidente.responsable %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @incidente.tipo %>
</p>

<p>
  <strong>Prioridad:</strong>
  <%= @incidente.prioridad %>
</p>

<%= link_to 'Editar', edit_incidente_path(@incidente) %> |
<%= link_to 'Atrás', incidentes_path %>
</div> 

app/views/incidentes/sobre.html.erb
<h2>Sobre esta aplicación</h2>
<div class="jumbotron center">
       	<td>
	      	Esta aplicación permite la gestión de incidentes por medio de una interfaz web. Esto incluye: Alta, baja y modificación de cada incidente ingresado en el sistema. <br><br>
	        El sistema despliega estos incidentes en un tabla, la cual al clickear en la cabecera de una columna, será ordenada discriminando por el atributo clickeado. También, provee una herramienta de búsqueda personalizada, la cual permite filtrar los incidentes por cualquiera de sus atributos y bajo más de un criterio. <br><br>
	        El sistema se encarga de ilustrar en una gráfica de torta el total de incidentes cargados, discriminando por el tipo.
	   	</td>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @titulo %></title>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'incidentes/header' %> 

<div class=container>
  <%= yield %>

</body>
</html>